package msi.crool.recycleview

object TaskList {
    val tasklist= listOf<Task>(
        Task("Take a walk", "7:00am"),
        Task("Buy groceries", "8:00am"),
        Task("Call mom", "9:00am"),
        Task("Attend meeting", "10:00am"),
        Task("Write report", "11:00am"),
        Task("Lunch with friend", "12:00pm"),
        Task("Go to the gym", "1:00pm"),
        Task("Pick up laundry", "2:00pm"),
        Task("Read a book", "3:00pm"),
        Task("Walk the dog", "4:00pm"),
        Task("Prepare dinner", "5:00pm"),
        Task("Watch TV", "6:00pm"),
        Task("Relax", "7:00pm"),
        Task("Plan tomorrow", "8:00pm"),
        Task("Call Jane", "9:00pm"),
        Task("Meditate", "10:00pm"),
        Task("Review day", "11:00pm"),
        Task("Set alarm", "12:00am"),
        Task("Prepare presentation", "1:00am"),
        Task("Update website", "2:00am"),
        Task("Write blog post", "3:00am"),
        Task("Check emails", "4:00am"),
        Task("Organize desk", "5:00am"),
        Task("Update calendar", "6:00am"),
        Task("Go for a run", "7:00am"),
        Task("Buy supplies", "8:00am"),
        Task("Meeting with team", "9:00am"),
        Task("Complete assignment", "10:00am"),
        Task("Make phone calls", "11:00am"),
        Task("Lunch break", "12:00pm"),
        Task("Visit the dentist", "1:00pm"),
        Task("Grocery shopping", "2:00pm"),
        Task("Clean the house", "3:00pm"),
        Task("Cook dinner", "4:00pm"),
        Task("Family time", "5:00pm"),
        Task("Go for a walk", "6:00pm"),
        Task("Read news", "7:00pm"),
        Task("Write emails", "8:00pm"),
        Task("Watch movie", "9:00pm"),
        Task("Relax with music", "10:00pm"),
        Task("Prepare for bed", "11:00pm"),
        Task("Sleep", "12:00am"),
        Task("Wake up", "1:00am"),
        Task("Exercise", "2:00am"),
        Task("Write journal", "3:00am"),
        Task("Plan day", "4:00am"),
        Task("Meditate", "5:00am"),
        Task("Read book", "6:00am"),
        Task("Prepare breakfast", "7:00am")
    )
}